import { connectDB } from "./mongodb";
import { PlaybookRule } from "./models";

export async function seedPlaybooks() {
  await connectDB();
  const playbooks = [
    {
      clauseType: "confidentiality",
      preferredLanguage: "The Recipient shall maintain the Confidential Information in strict confidence and shall not disclose it to any third party without the prior written consent of the Disclosing Party. Confidential Information shall be used solely for the purpose of evaluating and performing under this Agreement and shall not be used for any other purpose without the prior written consent of the Disclosing Party.",
      mustHaveTerms: "Definition of confidential information, exclusions, term of confidentiality (minimum 3 years post-termination), permitted disclosures, return/destruction obligation",
      fallbackTerms: "5 year survival for confidentiality obligations; mutual confidentiality for two-way exchanges",
      redFlags: "No survival period; one-way only without justification; no exclusions for publicly available information; overly broad definition including oral disclosures",
      negotiationPosture: "push_hard",
      indiaNote: "Indian courts require confidentiality clauses to be specific and not overly broad. Section 72A of IT Act 2000 provides statutory protection for data breaches. Ensure DPDP Act 2023 compliance for personal data.",
      sampleApprovedWording: "Confidential Information shall mean all information disclosed in writing and marked confidential, or disclosed orally and confirmed in writing within 15 days. The Recipient shall hold such information in confidence for 5 years from termination of this Agreement.",
    },
    {
      clauseType: "data_protection",
      preferredLanguage: "Each Party shall comply with all applicable data protection laws including the Digital Personal Data Protection Act, 2023 and any rules thereunder. Personal Data shall be processed only for the specified purpose and in accordance with the Data Principal's consent. Appropriate technical and organizational measures shall be implemented to ensure security of personal data.",
      mustHaveTerms: "DPDP Act compliance, data localization requirements, consent mechanism, purpose limitation, data retention period, breach notification (72 hours), data principal rights",
      fallbackTerms: "Reasonable security practices as per ISO 27001 or equivalent; data processing only within India",
      redFlags: "No DPDP Act reference; unrestricted cross-border transfer; no data retention/deletion schedule; no breach notification timeline",
      negotiationPosture: "push_hard",
      indiaNote: "DPDP Act 2023 requires: (1) consent before processing personal data, (2) notice specifying purpose, (3) data principal rights including right to erasure, (4) breach notification to Data Protection Board, (5) data localization for notified classes. Penalties up to INR 250 crore.",
      sampleApprovedWording: "The Processor shall process Personal Data only to the extent necessary to perform the Services and in compliance with the DPDP Act, 2023. The Processor shall implement appropriate technical and organizational measures including encryption, access controls, and regular security audits.",
    },
    {
      clauseType: "sub_processing",
      preferredLanguage: "The Processor shall not engage any Sub-Processor without the prior written consent of the Controller. Any approved Sub-Processor shall be bound by written agreement that imposes data protection obligations no less onerous than those in this Agreement. The Processor shall remain fully liable for all acts and omissions of its Sub-Processors.",
      mustHaveTerms: "Prior written approval requirement, minimum 30 days notice for sub-processor changes, right to object, liability flow-down, list of authorized sub-processors",
      fallbackTerms: "General consent for sub-processors in same group companies; 15 day notice period; right to object without unreasonable withholding",
      redFlags: "Unrestricted right to engage sub-processors; no liability for sub-processor acts; no notice requirement; no right to object",
      negotiationPosture: "push_hard",
      indiaNote: "Under DPDP Act, 2023, the data processor must obtain consent from the data fiduciary before engaging any sub-processor. Indian companies often resist sub-processor restrictions but should maintain control for DPDP compliance.",
      sampleApprovedWording: "Processor may engage Sub-Processors from its approved list (Schedule A) with 30 days prior notice. Controller may object within 15 days. Processor shall ensure all Sub-Processors comply with DPDP Act obligations.",
    },
    {
      clauseType: "audit_rights",
      preferredLanguage: "The Controller shall have the right, upon 15 days prior notice, to audit the Processor's facilities, systems, and records relating to processing of Personal Data. The Processor shall cooperate fully and provide access to all relevant documentation. Audit costs shall be borne by the Controller unless a material non-compliance is discovered.",
      mustHaveTerms: "Annual audit right, scope including sub-processors, 15 day notice, right to conduct on-site or via third-party auditor, remediation obligations",
      fallbackTerms: "Audit every 18 months; SOC 2 Type II reports accepted in lieu of on-site audit; 30 day notice period; reasonable scope limitations",
      redFlags: "No audit rights; audit only with consent; no sub-processor audit; unlimited audit frequency disrupting business",
      negotiationPosture: "negotiable",
      indiaNote: "DPDP Act requires data fiduciaries to conduct periodic audits. Indian IT vendors often push back on broad audit rights - negotiate for agreed scope and reasonable frequency.",
      sampleApprovedWording: "Controller may conduct one audit per calendar year upon 15 business days notice. Audit shall be limited to data processing activities and shall not unreasonably disrupt Processor's business operations.",
    },
    {
      clauseType: "breach_notification",
      preferredLanguage: "The Processor shall notify the Controller within 24 hours of becoming aware of any Personal Data Breach. Notification shall include: (a) nature of the breach, (b) categories of data affected, (c) number of data principals affected, (d) contact details of the data protection officer, (e) likely consequences, and (f) measures taken or proposed to mitigate the breach.",
      mustHaveTerms: "24 hour notification, detailed incident report, remediation plan, regulatory notification cooperation, breach response costs",
      fallbackTerms: "48 hour notification for non-personal data; 72 hour notification as per DPDP Act requirements; mutual breach notification obligations",
      redFlags: "No specific timeframe; notification only 'as soon as reasonably practicable'; no content requirements for notification; no cooperation obligation",
      negotiationPosture: "push_hard",
      indiaNote: "DPDP Act, 2023 Section 8(6) requires breach notification to Data Protection Board. Rule 7(2) specifies 72 hour notification. Breach of personal data affecting data principals requires individual notification. Failure to report may attract penalties up to INR 250 crore.",
      sampleApprovedWording: "Processor shall notify Controller within 24 hours of detecting a breach. A detailed root cause analysis shall be provided within 5 business days. Processor shall fully cooperate with regulatory notifications required under DPDP Act.",
    },
    {
      clauseType: "limitation_of_liability",
      preferredLanguage: "Neither Party shall be liable to the other for any indirect, incidental, special, consequential or punitive damages. Each Party's aggregate liability under this Agreement shall not exceed the total fees paid or payable by the Customer to the Provider during the 12 months preceding the claim. Liability cap shall not apply to: (a) breach of confidentiality, (b) data protection obligations, (c) indemnification obligations, (d) gross negligence or willful misconduct, (e) IP infringement.",
      mustHaveTerms: "Liability cap at minimum 12 months fees, carve-outs for confidentiality breach, data protection breach, IP infringement, willful misconduct, gross negligence",
      fallbackTerms: "Liability cap at 18-24 months fees; uncapped for data protection breaches; mutual liability caps",
      redFlags: "Zero liability for data breach; unilateral cap only benefiting one party; no carve-outs for IP infringement; liability cap less than 6 months fees",
      negotiationPosture: "push_hard",
      indiaNote: "Indian courts under the Indian Contract Act, 1872 generally uphold liability caps unless they violate Section 28 (restraint of legal proceedings) or are unconscionable. For data processing agreements, unlimited liability for data breaches is becoming market standard due to DPDP Act penalties.",
      sampleApprovedWording: "Liability cap shall be 12 months fees. This cap shall not apply to: (i) breach of confidentiality obligations, (ii) data protection obligations, (iii) indemnification of third party IP claims, or (iv) gross negligence or willful misconduct.",
    },
    {
      clauseType: "indemnity",
      preferredLanguage: "The Provider shall indemnify, defend and hold harmless the Customer from and against all claims, damages, losses, liabilities, and expenses arising out of or related to: (a) any breach of this Agreement by the Provider, (b) any infringement of intellectual property rights, (c) any breach of applicable law by the Provider including DPDP Act, 2023, and (d) gross negligence or willful misconduct of the Provider's personnel.",
      mustHaveTerms: "IP infringement indemnity, data breach indemnity, breach of confidentiality indemnity, mutual indemnity, control of defense, duty to mitigate",
      fallbackTerms: "Capped indemnity for breach of agreement; mutual IP indemnity; claims cooperation obligation; reasonable legal fee recovery",
      redFlags: "No IP infringement indemnity; no data breach indemnity; indemnity cap that prevents full recovery; sole control of defense without customer input",
      negotiationPosture: "push_hard",
      indiaNote: "Under Indian contract law, indemnity clauses are governed by Section 124 of Indian Contract Act. Courts have held that indemnity should cover all losses arising from the specified event. For data breaches, uncapped indemnity is increasingly expected under DPDP Act.",
      sampleApprovedWording: "Provider shall indemnify Customer against all third party claims arising from: (a) Provider's breach of data protection obligations, (b) IP infringement by Provider's technology, and (c) Provider's gross negligence. Customer shall provide prompt notice and reasonable cooperation.",
    },
    {
      clauseType: "dispute_resolution",
      preferredLanguage: "Any dispute arising out of or in connection with this Agreement shall first be resolved through good faith negotiations between the Parties. If not resolved within 30 days, the dispute shall be finally settled by arbitration in accordance with the Arbitration and Conciliation Act, 1996. The arbitration shall be conducted in [City], India, by a sole arbitrator mutually appointed. The language of arbitration shall be English.",
      mustHaveTerms: "Governing law (India), seat of arbitration (Indian city), Arbitration and Conciliation Act 1996, sole arbitrator or panel, language, costs",
      fallbackTerms: "Arbitration in Mumbai or Delhi; either sole arbitrator or 3-member panel for larger disputes; ICC or SIAC rules as alternative; appeals only on question of law",
      redFlags: "Foreign seat of arbitration for India-centric contracts; no specified arbitration act; no timeline for appointment; unilateral right to choose arbitrator",
      negotiationPosture: "standard",
      indiaNote: "Indian courts strongly prefer arbitration seated in India for contracts involving Indian parties. Section 36 of Arbitration Act provides for enforcement. For international counterparties, consider Singapore (SIAC) or London (LCIA) as neutral seats. Ensure the seat and governing law are clearly distinguished.",
      sampleApprovedWording: "Governing law: India. Arbitration: Mumbai, sole arbitrator, English language, Arbitration and Conciliation Act, 1996. Courts in Mumbai have exclusive jurisdiction for interim relief and enforcement.",
    },
    {
      clauseType: "governing_law",
      preferredLanguage: "This Agreement shall be governed by and construed in accordance with the laws of India. The Courts in [City], India shall have exclusive jurisdiction over any matters arising out of or relating to this Agreement.",
      mustHaveTerms: "Laws of India, exclusive jurisdiction, specific Indian city, separation of governing law from arbitration",
      fallbackTerms: "Non-exclusive jurisdiction; courts of Delhi/Mumbai/Bangalore; submission to arbitration",
      redFlags: "Foreign governing law for domestic contracts; no jurisdiction clause; submission to multiple jurisdictions",
      negotiationPosture: "push_hard",
      indiaNote: "For Indian contracts, governing law must be India. Even for international contracts involving Indian parties, ensure Indian law governs domestic obligations. Recent Indian court decisions have narrowed the scope for choosing foreign law in India-centric contracts.",
      sampleApprovedWording: "This Agreement shall be governed by the laws of India. The courts at New Delhi shall have exclusive jurisdiction to adjudicate any non-arbitrable disputes.",
    },
    {
      clauseType: "termination",
      preferredLanguage: "Either Party may terminate this Agreement upon 30 days written notice to the other Party. Either Party may terminate this Agreement immediately by written notice if the other Party: (a) commits a material breach that remains uncured for 30 days after written notice, (b) becomes insolvent or files for bankruptcy, or (c) ceases business operations. Upon termination, each Party shall return or destroy the other Party's Confidential Information.",
      mustHaveTerms: "Notice period, cure period, material breach definition, termination for cause, post-termination assistance, data return/deletion",
      fallbackTerms: "60 day notice for convenience; 30 day cure period; termination for cause only; transition assistance period; data export rights",
      redFlags: "Termination for convenience only by one party; no cure period; no data return obligation; immediate termination without cause",
      negotiationPosture: "negotiable",
      indiaNote: "Under Indian Contract Act, parties can agree on termination terms. Courts generally uphold termination clauses. For service agreements, ensure adequate transition period. DPDP Act requires data deletion upon termination of processing purpose.",
      sampleApprovedWording: "Either Party may terminate with 30 days notice. Termination for material breach requires 30 day cure period. Provider shall provide 60 days transition assistance and return/destroy all Customer data within 30 days.",
    },
    {
      clauseType: "ip_ownership",
      preferredLanguage: "All Intellectual Property Rights in the Deliverables shall vest exclusively with the Customer. The Provider hereby assigns all rights, title, and interest in the Deliverables to the Customer. The Provider retains the right to use general knowledge, skills, and experience and any pre-existing IP.",
      mustHaveTerms: "Customer ownership of deliverables, assignment of IP, work-for-hire, pre-existing IP carve-out, license for Customer pre-existing IP",
      fallbackTerms: "Joint ownership of improvements; license back to provider for internal use; royalty-free license for provider's tools",
      redFlags: "Provider retains ownership of all deliverables; no assignment clause; unlimited license to provider for customer IP; no IP warranty",
      negotiationPosture: "push_hard",
      indiaNote: "Under Indian Copyright Act, 1957, works created under contract are owned by the contractor unless there is a written assignment. Ensure written assignment of all IP deliverables. Indian courts strictly interpret IP assignment clauses.",
      sampleApprovedWording: "All work product shall be the exclusive property of Customer. Provider assigns all IP rights in deliverables. Provider retains a non-exclusive license to use general purpose tools and libraries incorporated in the deliverables.",
    },
    {
      clauseType: "payment",
      preferredLanguage: "Customer shall pay Provider the fees as set forth in the applicable Statement of Work. Invoices shall be paid within 30 days of receipt. Late payments shall accrue interest at 1.5% per month or the highest rate permitted by law. All fees are exclusive of applicable taxes.",
      mustHaveTerms: "Payment terms, late payment interest, tax responsibility, invoicing schedule, dispute mechanism for invoices",
      fallbackTerms: "45 day payment terms; 1% monthly late interest; quarterly invoicing; good faith dispute with holding of disputed amounts",
      redFlags: "Prepayment required for all services; no late fee cap; automatic price escalation; exclusive tax burden on customer",
      negotiationPosture: "standard",
      indiaNote: "Indian GST applies at 18% for most services. TDS under Income Tax Act applies at 2% (technical services) or 10% (professional fees). Ensure compliance with CBDT circulars on withholding tax.",
      sampleApprovedWording: "Fees invoiced quarterly and payable within 30 days. Late payment interest at 1% per month. Customer may withhold disputed amounts in good faith. All taxes additional.",
    },
    {
      clauseType: "sla",
      preferredLanguage: "Provider shall maintain Service Availability of at least 99.9% measured monthly. If Service Availability falls below the SLA threshold, Customer shall be eligible for Service Credits as follows: (a) 99.0-99.9%: 5% credit, (b) 95.0-98.9%: 10% credit, (c) below 95%: 25% credit. Maximum total credits in any month shall not exceed 50% of monthly fees.",
      mustHaveTerms: "Uptime percentage, measurement period, exclusion categories, service credit calculation, credit cap, right to terminate for persistent failure",
      fallbackTerms: "99.5% availability for standard services; 99.95% for critical services; credits as discount on future invoices; termination after 3 consecutive months below threshold",
      redFlags: "No SLA; availability below 99.5%; no service credits, credits only as 'goodwill'; unilateral exclusion categories; no termination right",
      negotiationPosture: "negotiable",
      indiaNote: "Indian IT services market typically expects at least 99.5% uptime for cloud services. Service credits are the standard remedy. Ensure exclusions are reasonable and don't defeat the SLA.",
      sampleApprovedWording: "Provider guarantees 99.9% monthly uptime. Credits: 5% for 99-99.9%, 10% for 95-99%, 25% below 95%. Max credit 50% of monthly fee. Customer may terminate if SLA missed 3 consecutive months.",
    },
    {
      clauseType: "non_solicit",
      preferredLanguage: "During the Term and for 12 months thereafter, neither Party shall directly or indirectly solicit or hire any employee of the other Party who has been involved in the services under this Agreement. This restriction shall not apply to general advertisements or hiring through public recruitment agencies not specifically targeting the other Party's employees.",
      mustHaveTerms: "12 month restriction, mutual obligation, exclusion for general advertising, materiality threshold, liquidated damages",
      fallbackTerms: "6 month restriction; key employee list only; no solicitation but no hiring restriction; damages equal to recruitment costs",
      redFlags: "Unilateral restriction; >12 month period; no exclusions for general hiring; hiring freeze of all employees; liquidated damages without cap",
      negotiationPosture: "negotiable",
      indiaNote: "Indian courts under Section 27 of Indian Contract Act, 1872 generally void agreements in restraint of trade. Non-solicit clauses are enforceable if they are reasonable in scope, duration, and geography. Courts have upheld 12 month non-solicit as reasonable.",
      sampleApprovedWording: "Neither Party shall solicit any employee of the other for 12 months post-termination. General public advertisements are permitted. Key employees may be listed in a schedule.",
    },
    {
      clauseType: "assignment",
      preferredLanguage: "Neither Party may assign this Agreement or any rights hereunder without the prior written consent of the other Party, which consent shall not be unreasonably withheld or delayed. This Agreement shall be binding upon and inure to the benefit of the permitted successors and assigns.",
      mustHaveTerms: "Mutual consent requirement, no unreasonable withholding, binding on successors, exception for merger/acquisition",
      fallbackTerms: "Assignment to affiliates without consent; 30 day notice for assignment; consent not required for change of control",
      redFlags: "Unrestricted assignment right; no consent requirement; assignment to competitors; no notice of assignment",
      negotiationPosture: "standard",
      indiaNote: "Under Indian Contract Act, contractual rights can be assigned unless expressly prohibited. Ensure assignment clause is mutual. For confidentiality reasons, parties often restrict assignment to competitors.",
      sampleApprovedWording: "Neither Party may assign this Agreement without consent, not to be unreasonably withheld. Assignment to affiliates or upon change of control with 30 days notice permitted.",
    },
    {
      clauseType: "warranty",
      preferredLanguage: "Provider warrants that: (a) the Services will be performed in a professional and workmanlike manner, (b) the Deliverables will conform to the specifications in the applicable SOW, (c) the Provider has the requisite rights to provide the Deliverables, and (d) the Services will comply with applicable laws including DPDP Act, 2023.",
      mustHaveTerms: "Service warranty, workmanship standard, specification conformance, IP non-infringement, legal compliance, warranty period, exclusion for customer misuse",
      fallbackTerms: "90 day warranty period for services; 12 month warranty for deliverables; remedy of re-performance or refund; mutual warranties",
      redFlags: "No warranties whatsoever; 'as is' delivery; disclaimer of all implied warranties; warranty only for 30 days; no remedy for breach",
      negotiationPosture: "standard",
      indiaNote: "Under Indian law, the Sale of Goods Act, 1930 implies certain warranties. For services, ensure express warranties covering: compliance with Indian law, DPDP Act compliance, and professional standard of care.",
      sampleApprovedWording: "Provider warrants services will conform to SOW specifications and be performed in a professional manner. Warranty period: 90 days from delivery. Remedy: re-performance or refund at Customer's option.",
    },
  ];

  for (const rule of playbooks) {
    await PlaybookRule.findOneAndUpdate(
      { clauseType: rule.clauseType },
      { $set: rule },
      { upsert: true, new: true }
    );
  }
}
